#![warn(missing_docs)]
#![cfg_attr(docsrs, feature(doc_cfg))]

//! Build pipelines that turn structured datasets into vector embeddings.
//!
//! `lvv` provides the pieces needed to load records, generate embeddings with
//! Ollama or OpenAI, cache those embeddings, and write the result to Qdrant or
//! another [`db::Sink`]. Jobs can be collected in a [`jobs::job_queue::JobQueue`]
//! and sent to more than one sink in registration order.
//!
//! # Pipeline
//!
//! 1. Create an [`intake::dataset::DataSet`] directly or read records through
//!    an [`intake::source::Source`].
//! 2. Describe the embedding request with [`jobs::job::JobBuilder`].
//! 3. Add one or more [`db::Sink`] implementations to a
//!    [`jobs::job_queue::JobQueue`] and call its `run` method.
//!
//! # Typed records
//!
//! Records that already exist as Rust types can describe their own points.
//! Implement [`transform::transform::VectorDatabaseItem`], or derive it with
//! the `derive` feature, and each value becomes a
//! [`transform::transform::VectorPointDraft`]: a category, the text to embed,
//! and the payload to store with the vector. See [`transform::transform`].
//!
//! # Transforming records with LLMs
//!
//! Records can be rewritten by a chat model before they are embedded: to
//! summarize long text, extract keywords, translate, or clean up inconsistent
//! fields. [`inference::CompletionModel`] sends each record as JSON to an
//! Ollama or OpenAI model, with your instructions as the system prompt, and
//! returns the responses. Store a response in a field of its record through
//! [`inference::completion_model::FieldEnhanceable`], then embed the updated
//! records. With the `derive` feature, marking that field
//! `#[lvv(description)]` makes the response part of the embedded text.
//!
//! Records that fail are left out of the results instead of returning an
//! error, so compare the number of responses with the number of records. See
//! [`inference::CompletionModel`] for examples.
//!
//! # Backends and environment variables
//!
//! Ollama uses `OLLAMA_URL`, defaulting to `http://127.0.0.1:11434`. OpenAI
//! reads `OPENAI_API_KEY`, and remote Qdrant configuration reads
//! `QDRANT_API_KEY`. Both load a `.env` file first and fail if there isn't
//! one.
//!
//! # Cargo features
//!
//! None are enabled by default.
//!
//! | Feature    | Enables |
//! |------------|---------|
//! | `derive`   | `#[derive(VectorDatabaseItem)]` and `#[derive(VectorDatabase)]` from [`lvv-macros`](https://docs.rs/lvv-macros), re-exported in [`transform::transform`] |
//! | `postgres` | `intake::PostgresSource` and `db::PostgresSink` |
//! | `sql`      | `intake::SqlSource` for SQLite and MySQL |
//! | `http`     | `intake::HttpSource` for paginated JSON APIs |
//!
//! # Example
//!
//! ```no_run
//! use lvv::{
//!     db::{Distance, QdrantSink},
//!     db::vector_database::{DatabaseParams, Location},
//!     intake::dataset::DataSet,
//!     jobs::{JobBuilder, Provider},
//!     jobs::job_queue::JobQueue,
//! };
//! use std::sync::Arc;
//!
//! # async fn example() -> anyhow::Result<()> {
//! let dataset = DataSet::new("articles.json", "articles", vec![
//!     serde_json::json!({"title": "Rust documentation"}),
//! ]);
//! let job = JobBuilder::default()
//!     .dataset(dataset)
//!     .provider(Provider::Ollama("nomic-embed-text".into()))
//!     .dims(768_u64)
//!     .extends(false)
//!     .distance(Distance::Cosine)
//!     .collection_name()
//!     .build()?;
//!
//! let params = DatabaseParams::new(
//!     Location::new_local("http://localhost:6334"),
//!     "articles".into(),
//!     Distance::Cosine,
//!     768,
//! );
//! let mut queue = JobQueue::from_vec(vec![job]);
//! queue.with_sink(Arc::new(QdrantSink::new(params)));
//! queue.run().await?;
//! # Ok(())
//! # }
//! ```

/// Reusable embedding cache support.
pub mod cache;
/// Vector database connections and pipeline sinks.
pub mod db;
/// Completion and embedding model clients.
pub mod inference;
/// Dataset types and source connectors.
pub mod intake;
/// Embedding jobs and queue execution.
pub mod jobs;
/// Typed records as vector points, with optional derive macros.
pub mod transform;

/// Re-exports for code generated by `lvv-macros`, so users don't need these as
/// direct dependencies. Not public API.
#[doc(hidden)]
pub mod __private {
    pub use anyhow;
    pub use qdrant_client::Payload;
    pub use serde;
    pub use serde_json;
}
